/* ================================== Project Euler. Problem #2 ====================================
*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
* By starting with 1 and 2, the first 10 terms will be:
*
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values do not exceed four million,
* find the sum of the even-valued terms.
*
* ----------------------------------------------------------------------------------------------- */

#include <iostream>

int main()
{
    int F1=1, F2=2, Faux;
    int S = 0, limit;

    std::cout << "Establezca un límite: ";
    std::cin >> limit;

    while(F2<limit){
        if(F2%2 == 0)
            S += F2;
        
        Faux = F1;
        F1 = F2;
        F2 += Faux;
    }

    std::cout << "La suma de los números de fibonacci pares menores a " 
              << limit << " es: " << S << std::endl;

    return 0;
}