// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first terms will be:
// 1, 2, 3, 4, 8, 13, 21, 34, 55, 89
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

use std::io;

fn main() {
    let limit = loop {
        println!("Select a limit: ");

        let mut input = String::new();
        io::stdin()
            .read_line(&mut input)
            .expect("Failed reading the input");

        match input.trim().parse() {
            Ok(num) => break num,
            Err(_) => {
                println!("The input was not a number, try again...");
                continue;
            }
        };
    };

    let sum_fib = sum_fibbonacci(limit);
    println!("The sum of even fibbonacci number below {limit} is {sum_fib}");
}

fn sum_fibbonacci(limit: u64) -> u64 {
    let mut sum: u64 = 0;
    let mut f_n: u64 = 1;
    let mut f_nxt: u64 = 2;
    while f_n < limit {
        // Sum if the current fibbonacci number is even
        if f_n % 2 == 0 {
            sum += f_n;
        }
        // Calc of next fibbonacci number
        let f_prev = f_n;
        f_n = f_nxt;
        f_nxt += f_prev;
    }
    sum
}
