# ========== Project Euler. Problem #2 ==========

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# -----------------------------------------------

# Función que suma los números de Fibonacci pares hasta n.
def SumEvenFib(n):
    S = 0
    F = 1
    Fn = 2

    while(Fn<n):
        if(Fn%2==0):
            S += Fn

        Fn, F = Fn+F, Fn

    return S

n = 4000000

print(f"La suma de los números de Fibonacci pares menores que {n} es {SumEvenFib(n)}")